name: Go Good First Issue

on:
  schedule:
    - cron: '*/5 * * * *'  # Set your desired cron schedule

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      ISSUE_COUNT: ${{ secrets.ISSUE_COUNT }}
      EMAIL: ${{ secrets.EMAIL }}
      NAME: ${{ secrets.NAME }}
      CRON_TIME: ${{ secrets.CRON_TIME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build and run Go application
      run: |
        go mod download
        go run main.go
